# Quasi newton methods (Broyden's)

In [172]:
import numpy as np

In [173]:
def f(x):
    return np.array(
        [x[0] + 0.5 * (x[0] - x[1])**3 - 1.0, 0.5 * (x[1] - x[0])**3 + x[1]]
    ).reshape(2, 1)
 
def jacobian():
    return np.array([[1,2],
             [2, 16]])

iteration = 10

In [174]:
x_p = np.array([0, 0]).reshape(2, 1)
f_p = f(x_p)
B_0 = jacobian()
H_0 = np.linalg.inv(B_0)

In [175]:
x_k = x_p - H_0 @ f_p
f_k = f(x_k)
H_p = H_0

print((x_p - x_k) - H_k @ (f_k - f_p), x_p)

[[-2.66666667]
 [ 0.33333333]] [[0]
 [0]]


In [176]:
for i in range(iteration):
    s_k = x_k - x_p
    y_k = f(x_k) - f(x_p)
    
    H_k = H_p + (s_k - H_p @ y_k) @ (s_k.T @ H_k) / (s_k.T @ H_p @ y_k)
    x_kp = x_k - H_kp @ y_k
    
    x_p = x_k
    x_k = x_kp
    H_p = H_k

print(x_k, f(x_k))

[[ 1.33333333]
 [-0.16666667]] [[ 2.02083333]
 [-1.85416667]]


In [106]:
from scipy import optimize

In [113]:
def fun(x):
    return [x[0]  + 0.5 * (x[0] - x[1])**3 - 1.0,
            0.5 * (x[1] - x[0])**3 + x[1]]

sol = optimize.broyden1(fun, [0, 0])
sol

array([0.84116396, 0.15883641])